### ISSUE TITLE
Everything seems broken

### ISSUE THREAD

**Issue by mstange** [dvander/moz-gfx-telemetry#8]
No graphs show up for me at the moment. The console says `TypeError: options is null`.

**Comment by dvander** [comment]
The other dropdowns work but it looks like the Telemetry job exported empty JSON for the frontpage data. Still investigating.

**Comment by dvander** [comment]
It seems to be working again. New non-pmo URL is: https://dvander.github.io/moz-gfx-telemetry/www/
